spring.application.name=backend

# Configuración del Apache Tomcat Embedded
server.servlet.context-path=/roosevelt
#server.port=8080
#CORS
#app.cors.allowed-origins=http://localhost:3000
#poner puerto o 

# Configuración de la base de datos (H2 en memoria)
# spring.datasource.url=jdbc:h2:file:./datos/users;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Configuración de conexión JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=false


# Carga inicial de datos

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.continue-on-error=false

# Configuración de Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Carga inical de datos usando archivos .sql
# => always     =>siempre
# => embedded   =>solo para H2 en memoria
# => never      =>nunca
